deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R imagenes $DEPLOYPATH
    - /bin/cp -R javascript $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R composer.json $DEPLOYPATH